### ISSUE TITLE
issue with Altair library. 

### ISSUE THREAD

**Issue by sdeanda99** [hassancs91/AI-Hosting-Advisor#1]
I  have version 4 install and tried upgrading to version 5 and still giving me errors. 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/streamlit", line 5, in <module>
    from streamlit.web.cli import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamlit/__init__.py", line 55, in <module>
    from streamlit.delta_generator import DeltaGenerator as _DeltaGenerator
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamlit/delta_generator.py", line 43, in <module>
    from streamlit.elements.arrow_altair import ArrowAltairMixin
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/streamlit/elements/arrow_altair.py", line 36, in <module>
    from altair.vegalite.v4.api import Chart
ModuleNotFoundError: No module named 'altair.vegalite.v4'
Tried putting this into requirements.txt still getting error 

altair<5
streamlit

**Comment by dibyendu2280** [comment]
When I used ui_sample.py(in a web form) it updated previously filled data every time. for example when I submit an answer for  "How important is 24/7 customer support to you?" then all previous assistance answers data is updated(so it uses a lot of tokens) along with that question's assistance answer. Sir, please solve this.
